config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get  'game',    to: 'static_pages#game'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def game
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppBattleship</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/game.html.erb
<code><h1>Welcome to RICHILL's Battelship! <%= link_to image_tag("ship.png"), "https://twitter.com/ArtLoe" %></h1></code>
<code><h3 classs="games"><%= link_to "Easy:Grid 7 game", root_path %> | <%= link_to "Advance:Grid 10 game", game_path %> | Game Info | <%= link_to "About Richill", 'http://richill.github.io' %></h3><code>

<div id="gameBoard">
  <code><div id="messageArea"></div></code>
  <table>
    <!-- row 1 -->
    <tr>
      <!-- <td id="#">J</td> -->
      <td id="00">A0</td>
      <td id="01">A1</td>
      <td id="02">A2</td>
      <td id="03">A3</td>
      <td id="04">A4</td>
      <td id="05">A5</td>
      <td id="06">A6</td>
      <td id="07">A7</td>
      <td id="08">A8</td>
      <td id="09">A9</td> 
    </tr>

    <!-- row 2 -->
    <tr>
      <td id="10">B0</td>
      <td id="11">B1</td>
      <td id="12">B2</td>
      <td id="13">B3</td>
      <td id="14">B4</td>
      <td id="15">B5</td>
      <td id="16">B6</td>
      <td id="17">B7</td>
      <td id="18">B8</td>
      <td id="19">B9</td>  
    </tr>

    <!-- row 3 -->
    <tr>
      <td id="20">C0</td>
      <td id="21">C1</td>
      <td id="22">C2</td>
      <td id="23">C3</td>
      <td id="24">C4</td>
      <td id="25">C5</td>
      <td id="26">C6</td>
      <td id="27">C7</td>
      <td id="28">C8</td>
      <td id="29">C9</td>
    </tr>

    <!-- row 4 -->
    <tr>
      <td id="30">D0</td>
      <td id="31">D1</td>
      <td id="32">D2</td>
      <td id="33">D3</td>
      <td id="34">D4</td>
      <td id="35">D5</td>
      <td id="36">D6</td>
      <td id="37">D7</td>
      <td id="38">D8</td>
      <td id="39">D9</td>
    </tr>

    <!-- row 5 -->
    <tr>
      <td id="40">E0</td>
      <td id="41">E1</td>
      <td id="42">E2</td>
      <td id="43">E3</td>
      <td id="44">E4</td>
      <td id="45">E5</td>
      <td id="46">E6</td>
      <td id="47">E7</td>
      <td id="48">E8</td>
      <td id="49">E9</td>
    </tr>

    <!-- row 6 -->
    <tr>
      <td id="50">F0</td>
      <td id="51">F1</td>
      <td id="52">F2</td>
      <td id="53">F3</td>
      <td id="54">F4</td>
      <td id="55">F5</td>
      <td id="56">F6</td>
      <td id="57">F7</td>
      <td id="58">F8</td>
      <td id="59">F9</td>
    </tr>

    <!-- row 7 -->
    <tr>
      <td id="60">G0</td>
      <td id="71">G1</td>
      <td id="72">G2</td>
      <td id="73">G3</td>
      <td id="74">G4</td>
      <td id="75">G5</td>
      <td id="76">G6</td>
      <td id="77">G7</td>
      <td id="78">G8</td>
      <td id="79">G9</td>
    </tr>

    <!-- row 8 -->
    <tr>
      <td id="80">H0</td>
      <td id="81">H1</td>
      <td id="82">H2</td>
      <td id="83">H3</td>
      <td id="84">H4</td>
      <td id="85">H5</td>
      <td id="86">H6</td>
      <td id="87">H7</td>
      <td id="88">H8</td>
      <td id="89">H9</td>
    </tr>

    <!-- row 9 -->
    <tr>
      <td id="90">I0</td>
      <td id="91">I1</td>
      <td id="92">I2</td>
      <td id="93">I3</td>
      <td id="94">I4</td>
      <td id="95">I5</td>
      <td id="96">I6</td>
      <td id="97">I7</td>
      <td id="98">I8</td>
      <td id="99">I9</td>
    </tr>

    <!-- row 10 -->
    <tr>
      <td id="100">J0</td>
      <td id="101">J1</td>
      <td id="102">J2</td>
      <td id="103">J3</td>
      <td id="104">J4</td>
      <td id="105">J5</td>
      <td id="106">J6</td>
      <td id="107">J7</td>
      <td id="108">J8</td>
      <td id="109">J9</td>
    </tr>
  </table>
  <form>
    <input type="text" id="guessInput" placeholder="type a cell # in caps eg: B0">
    <input type="button" id="fireButton" value="Fire!">
  </form>
</div>

app/views/static_pages/home.html.erb
<code><h1>Welcome to RICHILL's Battelship! <%= link_to image_tag("ship.png"), "https://twitter.com/ArtLoe" %></h1></code> 
<code><h3 classs="seven_grid"><%= link_to "Easy:Grid 7 game", root_path %> | <%= link_to "Advance:Grid 10 game", game_path %> | Game Info | <%= link_to "About Richill", 'http://richill.github.io' %></h3><code>

<div id="board">
  <code><div id="messageArea"></div></code>
  <table>
    <!-- row 1 -->
    <tr>
      <td id="00">A0</td>
      <td id="01">A1</td>
      <td id="02">A2</td>
      <td id="03">A3</td>
      <td id="04">A4</td>
      <td id="05">A5</td>
      <td id="06">A6</td>
    </tr>

    <!-- row 2 -->
    <tr>
      <!-- <td id="07"></td>
      <td id="08"></td>
      <td id="09"></td> -->
      <td id="10">B0</td>
      <td id="11">B1</td>
      <td id="12">B2</td>
      <td id="13">B3</td>
      <td id="14">B4</td>
      <td id="15">B5</td>
      <td id="16">B6</td>
    </tr>

    <!-- row 3 -->
    <tr>
      <!-- <td id="17"></td>
      <td id="18"></td>
      <td id="19"></td> -->
      <td id="20">C0</td>
      <td id="21">C1</td>
      <td id="22">C2</td>
      <td id="23">C3</td>
      <td id="24">C4</td>
      <td id="25">C5</td>
      <td id="26">C6</td>
    </tr>

    <!-- row 4 -->
    <tr>
      <!-- <td id="27"></td>
      <td id="28"></td>
      <td id="29"></td> -->
      <td id="30">D0</td>
      <td id="31">D1</td>
      <td id="32">D2</td>
      <td id="33">D3</td>
      <td id="34">D4</td>
      <td id="35">D5</td>
      <td id="36">D6</td>
    </tr>

    <!-- row 5 -->
    <tr>
      <!-- <td id="37"></td>
      <td id="38"></td>
      <td id="39"></td> -->
      <td id="40">E0</td>
      <td id="41">E1</td>
      <td id="42">E2</td>
      <td id="43">E3</td>
      <td id="44">E4</td>
      <td id="45">E5</td>
      <td id="46">E6</td>
    </tr>
    <!-- row 6 -->
    <tr>
      <!-- <td id="47"></td>
      <td id="48"></td>
      <td id="49"></td> -->
      <td id="50">F0</td>
      <td id="51">F1</td>
      <td id="52">F2</td>
      <td id="53">F3</td>
      <td id="54">F4</td>
      <td id="55">F5</td>
      <td id="56">F6</td>
    </tr>

    <!-- row 7 -->
    <tr>
      <!-- <td id="57"></td>
      <td id="58"></td>
      <td id="59"></td> -->
      <td id="60">G0</td>
      <td id="61">G1</td>
      <td id="62">G2</td>
      <td id="63">G3</td>
      <td id="64">G4</td>
      <td id="65">G5</td>
      <td id="66">G6</td>
    </tr>
  </table>
  <form>
    <input type="text" id="guessInput" placeholder="type a cell # in caps eg: B0">
    <input type="button" id="fireButton" value="Fire!">
  </form>
</div>